In [101]:
import pandas as pd
import numpy as np

In [78]:
pd.__version__

'3.0.6'

In [79]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-27 12:59:21--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.4’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.007s

2026-09-27 12:59:21 (85.3 MB/s) - ‘car_fuel_efficiency_2026.csv.4’ saved [635180/635180]

In [80]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [81]:
len(df)

10000

In [82]:
df.shape

(10000, 11)

In [83]:
df["fuel_type"].nunique()

3

In [84]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [85]:
df.isnull().sum().sum()

np.int64(1141)

In [86]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [87]:
df.loc[df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].idxmax()]

model_year                          2022
origin                              Asia
fuel_type                         Diesel
drivetrain             Front-wheel drive
num_doors                              4
engine_displacement                 1990
num_cylinders                          6
horsepower                         225.0
vehicle_weight                      3870
acceleration                        17.2
fuel_efficiency_mpg                 41.2
Name: 6354, dtype: object

In [88]:
df["horsepower"].median()

np.float64(254.0)

In [89]:
df["horsepower"].mode()[0]

np.float64(252.0)

In [92]:
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mode()[0])

In [93]:
df["horsepower"].median()

np.float64(252.0)

In [96]:
df_asia = df[df["origin"] == "Asia"]

In [97]:
df_asia = df_asia[['vehicle_weight', 'model_year']]

In [99]:
df_asia = df_asia.head(7)

In [100]:
df_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [102]:
X = df_asia.to_numpy()

In [103]:
XTX = X.T @ X

In [104]:
XTX_inv = np.linalg.inv(XTX)

In [105]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [107]:
w = XTX_inv @ X.T @ y

In [108]:
w.sum()

np.float64(0.36919696904925486)